name: Scan JS Repos

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'
  # - cron: '0 */3 * * *'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list
        run: |
          gh search repos \
            --archived=false \
            --visibility=public \
            --include-forks=only \
            --sort=updated \
            --language=JavaScript \
            --created='>2024-04' \
            --json='name,stargazersCount,language,updatedAt' \
            --limit=3 |
            tee reports/dummy.json
          # gh repo list --limit 300 --source --no-archived --json 'name,primaryLanguage,updatedAt' >reports/dummy.json
      - name: Commit
        run: |
          git diff
          git config --global user.email "bot@github.com"
          git config --global user.name "bot"
          git diff --quiet || (git add . && git commit -m "new report added")
          git push
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
