name: JUNK

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'
  # - cron: '0 */3 * * *'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  scan-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: scan
        run: bash .github/scripts/scan.sh
      - name: eval
        run: echo "bash .github/scripts/eval.sh"
        # run: bash .github/scripts/eval.sh
      - name: report
        run: echo "bash .github/scripts/report.sh"
        # run: bash .github/scripts/report.sh
      - name: Commit
        run: |
          git diff
          git config --global user.email "bot@github.com"
          git config --global user.name "bot"
          git diff --quiet || (git add . && git commit -m "new report added")
          git push
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
