name: Scan

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list
        run: |
          gh repo list --limit 300 --source --no-archived --json 'name,primaryLanguage,updatedAt' >reports/dummy.json
      - name: Commit
        run: |
          git diff
          git config --global user.email "bot@github.com"
          git config --global user.name "bot"
          git diff --quiet || (git add . && git commit -m "new report added")
          git push
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

